version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: api-helpdesk
        container_name: api-helpdesk-app
        restart: unless-stopped
        working_dir: /var/www/html

        user: "1000:1000"
        volumes:
            - .:/var/www/html
        environment:
            APP_ENV: local
            APP_DEBUG: ${APP_DEBUG:-true}
            APP_URL: api-helpdesk-dev.ifven.id

            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}

    nginx:
        image: nginx:stable-alpine
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
            - db

    db:
        image: postgres:15-alpine
        container_name: postgres_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
